apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo
  namespace: devplus
spec:
  interval: 5m
  chart:
    spec:
      chart: demowebchart
      version: 	0.1.1
      sourceRef:
        kind: HelmRepository
        name: webdevdemo
        namespace: flux-system
      interval: 1m
