apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demowebchart
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 1m0s
  ref:
    branch: dev
  secretRef:
    name: flux-system
  timeout: 20s
  url: https://github.com/malek1991/GitOpsFlux.git