apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demowebchart
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./environments/dev/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: demowebchart